In [15]:
import pandas as pd
starttime=pd.date_range('20190129', '20190130',freq='10Min') #生成一个时间段
starttime=pd.Series(starttime)

In [16]:
endtime=pd.date_range('201901290010', '20190130',freq='10Min') #生成一个时间段

In [17]:
endtime=pd.Series(endtime)

In [18]:
pd.DataFrame({'starttime':starttime,'endtime':endtime})

              starttime             endtime
0   2019-01-29 00:00:00 2019-01-29 00:10:00
1   2019-01-29 00:10:00 2019-01-29 00:20:00
2   2019-01-29 00:20:00 2019-01-29 00:30:00
3   2019-01-29 00:30:00 2019-01-29 00:40:00
4   2019-01-29 00:40:00 2019-01-29 00:50:00
5   2019-01-29 00:50:00 2019-01-29 01:00:00
6   2019-01-29 01:00:00 2019-01-29 01:10:00
7   2019-01-29 01:10:00 2019-01-29 01:20:00
8   2019-01-29 01:20:00 2019-01-29 01:30:00
9   2019-01-29 01:30:00 2019-01-29 01:40:00
10  2019-01-29 01:40:00 2019-01-29 01:50:00
11  2019-01-29 01:50:00 2019-01-29 02:00:00
12  2019-01-29 02:00:00 2019-01-29 02:10:00
13  2019-01-29 02:10:00 2019-01-29 02:20:00
14  2019-01-29 02:20:00 2019-01-29 02:30:00
15  2019-01-29 02:30:00 2019-01-29 02:40:00
16  2019-01-29 02:40:00 2019-01-29 02:50:00
17  2019-01-29 02:50:00 2019-01-29 03:00:00
18  2019-01-29 03:00:00 2019-01-29 03:10:00
19  2019-01-29 03:10:00 2019-01-29 03:20:00
20  2019-01-29 03:20:00 2019-01-29 03:30:00
21  2019-01-29 03:30:00 2019-01-29 03:40:00
22  2019-01-29 03:40:00 2019-01-29 03:50:00
23  2019-01-29 03:50:00 2019-01-29 04:00:00
24  2019-01-29 04:00:00 2019-01-29 04:10:00
25  2019-01-29 04:10:00 2019-01-29 04:20:00
26  2019-01-29 04:20:00 2019-01-29 04:30:00
27  2019-01-29 04:30:00 2019-01-29 04:40:00
28  2019-01-29 04:40:00 2019-01-29 04:50:00
29  2019-01-29 04:50:00 2019-01-29 05:00:00
..                  ...                 ...
115 2019-01-29 19:10:00 2019-01-29 19:20:00
116 2019-01-29 19:20:00 2019-01-29 19:30:00
117 2019-01-29 19:30:00 2019-01-29 19:40:00
118 2019-01-29 19:40:00 2019-01-29 19:50:00
119 2019-01-29 19:50:00 2019-01-29 20:00:00
120 2019-01-29 20:00:00 2019-01-29 20:10:00
121 2019-01-29 20:10:00 2019-01-29 20:20:00
122 2019-01-29 20:20:00 2019-01-29 20:30:00
123 2019-01-29 20:30:00 2019-01-29 20:40:00
124 2019-01-29 20:40:00 2019-01-29 20:50:00
125 2019-01-29 20:50:00 2019-01-29 21:00:00
126 2019-01-29 21:00:00 2019-01-29 21:10:00
127 2019-01-29 21:10:00 2019-01-29 21:20:00
128 2019-01-29 21:20:00 2019-01-29 21:30:00
129 2019-01-29 21:30:00 2019-01-29 21:40:00
130 2019-01-29 21:40:00 2019-01-29 21:50:00
131 2019-01-29 21:50:00 2019-01-29 22:00:00
132 2019-01-29 22:00:00 2019-01-29 22:10:00
133 2019-01-29 22:10:00 2019-01-29 22:20:00
134 2019-01-29 22:20:00 2019-01-29 22:30:00
135 2019-01-29 22:30:00 2019-01-29 22:40:00
136 2019-01-29 22:40:00 2019-01-29 22:50:00
137 2019-01-29 22:50:00 2019-01-29 23:00:00
138 2019-01-29 23:00:00 2019-01-29 23:10:00
139 2019-01-29 23:10:00 2019-01-29 23:20:00
140 2019-01-29 23:20:00 2019-01-29 23:30:00
141 2019-01-29 23:30:00 2019-01-29 23:40:00
142 2019-01-29 23:40:00 2019-01-29 23:50:00
143 2019-01-29 23:50:00 2019-01-30 00:00:00
144 2019-01-30 00:00:00                 NaT

[145 rows x 2 columns]

In [25]:
one=pd.read_csv(r'D:\Entertainment\Prediction of Metro Passenger Flow\Metro_train\record_2019-01-01.csv')

In [26]:
one.head()

,time,lineID,stationID,deviceID,status,userID,payType
0,2019/1/1 2:00,B,27,1354,0,D13f76f42c9a677c4add94d9e480fb5c5,3
1,2019/1/1 2:01,B,5,200,1,D9a337d37d9512184b8e3fd477934b293,3
2,2019/1/1 2:01,B,5,247,0,Dc9e179298617f40b782490c1f3e2346c,3
3,2019/1/1 2:02,B,5,235,0,D9a337d37d9512184b8e3fd477934b293,3
4,2019/1/1 2:03,B,23,1198,0,Dd1cde61886c23fdb7ef1fdb76c9b1234,3

In [33]:
one['time']=pd.to_datetime(one['time'])

#by_seconds = one.resample('time')

one['flag'] = one['time'].dt.minute%10==0


#one['time'].dt.floor('10T').diff()

In [34]:
one

,time,lineID,stationID,deviceID,status,userID,payType,flag
0,2019-01-01 02:00:00,B,27,1354,0,D13f76f42c9a677c4add94d9e480fb5c5,3,True
1,2019-01-01 02:01:00,B,5,200,1,D9a337d37d9512184b8e3fd477934b293,3,False
2,2019-01-01 02:01:00,B,5,247,0,Dc9e179298617f40b782490c1f3e2346c,3,False
3,2019-01-01 02:02:00,B,5,235,0,D9a337d37d9512184b8e3fd477934b293,3,False
4,2019-01-01 02:03:00,B,23,1198,0,Dd1cde61886c23fdb7ef1fdb76c9b1234,3,False
5,2019-01-01 02:04:00,B,3,109,0,D7a8fc96cbc11e5df389aa45a62870a48,3,False
6,2019-01-01 02:04:00,B,27,1354,1,D13f76f42c9a677c4add94d9e480fb5c5,3,False
7,2019-01-01 02:05:00,B,4,141,0,D3951ac47cb9911c7adca0f23a9eb9bf2,3,False
8,2019-01-01 02:05:00,B,23,1198,0,Db5682ca9db937733e95db27b959e62a1,3,False
9,2019-01-01 02:05:00,B,20,1036,1,D01d6584e23de32f8225c756f4c3add76,3,False
10,2019-01-01 02:05:00,B,5,234,1,D9a337d37d9512184b8e3fd477934b293,3,False
11,2019-01-01 02:05:00,B,20,1037,1,D49e8e27df37b8e9a764c3984b6b5af7a,3,False
12,2019-01-01 02:06:00,C,55,2631,1,D2cc37ddb3cd3444d1dae04ee41c2e54e,3,False
13,2019-01-01 02:06:00,B,5,194,0,D9a337d37d9512184b8e3fd477934b293,3,False
14,2019-01-01 02:06:00,A,77,3527,1,Dda23e1db8a8a07168deac17d6812aee0,3,False
15,2019-01-01 02:07:00,C,50,2417,1,D4b0a7f53a7cd008d40f1e6e29981d831,3,False
16,2019-01-01 02:07:00,C,41,1911,1,Dc1a9833ea40a4be1247e2ce554b6e418,3,False
17,2019-01-01 02:07:00,C,40,1872,1,Dc0965622e7e38455fb85d1b07c68c83a,3,False
18,2019-01-01 02:08:00,C,41,1909,0,Dc1a9833ea40a4be1247e2ce554b6e418,3,False
19,2019-01-01 02:09:00,A,77,3503,0,D474e239e1ba81f8011e8a856cab100ae,3,False
20,2019-01-01 02:10:00,C,55,2643,0,D2cc37ddb3cd3444d1dae04ee41c2e54e,3,True
21,2019-01-01 02:10:00,C,50,2431,0,D4b0a7f53a7cd008d40f1e6e29981d831,3,True
22,2019-01-01 02:11:00,C,61,2858,1,D6e1109735d8abc1f23ea01323dba0f45,3,False
23,2019-01-01 02:13:00,C,61,2858,1,D0f5bb42207a646a52d05183a5cb1cc1e,3,False
24,2019-01-01 02:14:00,C,61,2857,0,D0f5bb42207a646a52d05183a5cb1cc1e,3,False
25,2019-01-01 02:16:00,C,55,2631,1,D2cc37ddb3cd3444d1dae04ee41c2e54e,3,False
26,2019-01-01 02:16:00,B,31,1523,1,D4039032aa85719d9d451ed91a3f46e74,3,False
27,2019-01-01 02:16:00,B,31,1523,1,De684d6ae5ee60a2beca7cb3e81456cec,3,False
28,2019-01-01 02:17:00,B,31,1524,1,D9ba95a7e13d7bd0ceacf1d96f0a27bba,3,False
29,2019-01-01 02:17:00,B,31,1524,1,De6a5237779e44b05cba285bf32367837,3,False
...,...,...,...,...,...,...,...,...
1048545,2019-01-01 14:26:00,B,15,757,0,B9f104a9ca9d15a6c1ea6a1bcdea571a1,1,False
1048546,2019-01-01 14:26:00,B,9,443,0,Bc52c7b7094545d66bf7ecfba4abf6e23,1,False
1048547,2019-01-01 14:26:00,B,19,1003,0,Be1bd3b2fab7ec84a66f270ae36b7aaaa,1,False
1048548,2019-01-01 14:26:00,C,51,2469,0,B2dd302b33ffe61e641f9c558ee0e2129,1,False
1048549,2019-01-01 14:26:00,B,20,1053,0,B21d08fba3d2b94aa56afe86742a2e71a,1,False
1048550,2019-01-01 14:26:00,B,10,532,1,B3541d45792e422023f4783fb88179841,1,False
1048551,2019-01-01 14:26:00,B,33,1588,0,Be11a26fef69346a7dd9428009afd1d0b,1,False
1048552,2019-01-01 14:26:00,A,78,3556,0,B981e751e8fb6c90c4244816323b91251,1,False
1048553,2019-01-01 14:26:00,B,5,246,0,B1234afed28e0da84e795756d57d01e82,1,False
1048554,2019-01-01 14:26:00,A,78,3560,1,A2a86393483e9494eef8670095f29b2b9,0,False
1048555,2019-01-01 14:26:00,B,14,719,1,B874c1f5db9794de00c0f19dc884dc9cb,1,False
1048556,2019-01-01 14:26:00,C,47,2292,0,B88e00f542e43bf07a0822b70c2f652d7,1,False
1048557,2019-01-01 14:26:00,B,24,1237,0,Bf9857c514eed470dc10e9c2b3e215424,1,False
1048558,2019-01-01 14:26:00,B,22,1150,1,B148fca4c5c4e4cf661a3a4af8f3ab36c,1,False
1048559,2019-01-01 14:26:00,C,38,1789,0,B01471c368a40551f3fd074bcc27908dc,1,False
1048560,2019-01-01 14:26:00,B,2,75,1,B2aa23463199b11792b9ed5fd4002d25c,1,False
1048561,2019-01-01 14:26:00,B,25,1274,1,B41cba641c85e1e60d8bac9bd3d6aefd5,1,False
1048562,2019-01-01 14:26:00,A,77,3509,1,B09ee6e0ced0acfe97ce89be38e55db14,1,False
1048563,2019-01-01 14:26:00,B,9,455,1,A68cc5e16aafdd81eb6e7583f22a1dba1,0,False
1048564,2019-01-01 14:26:00,B,15,766,0,A1cfa7d7e69351f1811707613576aef1e,0,False
1048565,2019-01-01 14:26:00,C,63,2951,1,C582c7d78da0e2664aecc2a36de95103a,2,False
1048566,2019-01-01 14:26:00,B,21,1115,0,C8abec85a562b58ef350c5c5e146af428,2,False
1048567,2019-01-01 14:26:00,B,24,1223,1,Cf97e5d51050e14262e7a0c9a648caa4e,2,False
1048568,2019-01-01 14:26:00,B,13,685,1,C28b68f1d7cfaccad53c694f447c042a8,2,False
1048569,2019-01-01 14:26:00,A,78,3551,0,C8919b35ee9ac0377c2da032f2ebb13fb,2,False
1048570,2019-01-01 14:26:00,B,20,1049,0,C65a8726a88ab8276aa3104a58e553642,2,False
1048571,2019-01-01 14:26:00,C,46,2174,1,Cfc567b1041f3c0397ff6631fc504237f,2,False
1048572,2019-01-01 14:26:00,B,22,1147,0,Cc9efd746e72c7daeec30173b4dab7dfb,2,False
1048573,2019-01-01 14:26:00,B,20,1054,1,Ce66165675e4233a08a134d7a4853a4bc,2,False
1048574,2019-01-01 14:26:00,C,48,2322,0,C8455755db6950600d5234788130b09f5,2,False