In [5]:
import pandas as pd
ONE=pd.read_csv(r'D:\Entertainment\Prediction of Metro Passenger Flow\Metro_train\data21_25.csv')

In [8]:
ONE['time']=pd.to_datetime(ONE['time'])
ONE['year']=ONE['time'].dt.year
ONE['month']=ONE['time'].dt.month
ONE['day']=ONE['time'].dt.day
ONE['hour']=ONE['time'].dt.hour
ONE['minute']=ONE['time'].dt.minute
bins=[-1,0,10,20,30,40,50,60]
ONE['did']=pd.cut(ONE['minute'].values,bins,right=False)
first=ONE
first=first.sort_values(by='time')
# 进站人数
FIRST=first.loc[first['status']==1]
IN=FIRST.groupby(['year','month','day','hour','did','stationID'])['userID'].count().reset_index()
# 出站人数
SECOND=first.loc[first['status']==0]
OUT=SECOND.groupby(['year','month','day','hour','did','stationID'])['userID'].count().reset_index()
IN_OUT=pd.merge(IN,OUT,on=['year','month','day','hour','did','stationID'])
IN_OUT.rename(columns={'userID_x':"IN",'userID_y':'OUT'},inplace=True)

       year  month  day  hour       did  stationID  IN  OUT
0      2019      1   21     0   [0, 10)          5   3    3
1      2019      1   21     0   [0, 10)         23   1    1
2      2019      1   21     0   [0, 10)         30   1    2
3      2019      1   21     0   [0, 10)         77   1    1
4      2019      1   21     0  [10, 20)          5   3    1
5      2019      1   21     0  [10, 20)          6   2    1
6      2019      1   21     0  [10, 20)          7   2    2
7      2019      1   21     0  [10, 20)         23   1    1
8      2019      1   21     0  [10, 20)         77   1    1
9      2019      1   21     0  [10, 20)         79   1    1
10     2019      1   21     0  [20, 30)          1   1    1
11     2019      1   21     0  [20, 30)          5   2    1
12     2019      1   21     0  [20, 30)         10   1    1
13     2019      1   21     0  [20, 30)         30   2    2
14     2019      1   21     0  [20, 30)         50   1    1
15     2019      1   21     0  [20, 30)         70   1    1
16     2019      1   21     0  [20, 30)         73   1    1
17     2019      1   21     0  [20, 30)         80   6    2
18     2019      1   21     0  [30, 40)          5   2    2
19     2019      1   21     0  [30, 40)         10   2    1
20     2019      1   21     0  [30, 40)         30   2    3
21     2019      1   21     0  [30, 40)         39   3    1
22     2019      1   21     0  [30, 40)         41   1    1
23     2019      1   21     0  [30, 40)         45   2    1
24     2019      1   21     0  [30, 40)         55   1    1
25     2019      1   21     0  [30, 40)         56   1    1
26     2019      1   21     0  [30, 40)         59   4    1
27     2019      1   21     0  [30, 40)         80   4    3
28     2019      1   21     0  [40, 50)          5   1    2
29     2019      1   21     0  [40, 50)         29   2    2
...     ...    ...  ...   ...       ...        ...  ..  ...
42626  2019      1   25    23  [40, 50)         46   4   17
42627  2019      1   25    23  [40, 50)         47   2    3
42628  2019      1   25    23  [40, 50)         48   4    8
42629  2019      1   25    23  [40, 50)         49   1    3
42630  2019      1   25    23  [40, 50)         50   1    4
42631  2019      1   25    23  [40, 50)         51   8    9
42632  2019      1   25    23  [40, 50)         52   4    3
42633  2019      1   25    23  [40, 50)         53   2    4
42634  2019      1   25    23  [40, 50)         56   1   24
42635  2019      1   25    23  [40, 50)         57   2   36
42636  2019      1   25    23  [40, 50)         59   3    1
42637  2019      1   25    23  [40, 50)         61   1   22
42638  2019      1   25    23  [40, 50)         63   1   20
42639  2019      1   25    23  [40, 50)         78   2    4
42640  2019      1   25    23  [40, 50)         80   1    5
42641  2019      1   25    23  [50, 59)          5   4    2
42642  2019      1   25    23  [50, 59)          8   5    1
42643  2019      1   25    23  [50, 59)         10   4   11
42644  2019      1   25    23  [50, 59)         16   1   14
42645  2019      1   25    23  [50, 59)         17   3    3
42646  2019      1   25    23  [50, 59)         31   1    6
42647  2019      1   25    23  [50, 59)         32   1   13
42648  2019      1   25    23  [50, 59)         37   1   10
42649  2019      1   25    23  [50, 59)         38   1    3
42650  2019      1   25    23  [50, 59)         39   4    3
42651  2019      1   25    23  [50, 59)         44   2    2
42652  2019      1   25    23  [50, 59)         53   1    4
42653  2019      1   25    23  [50, 59)         56   1    8
42654  2019      1   25    23  [50, 59)         59   2   11
42655  2019      1   25    23  [50, 59)         74   2    2

[42656 rows x 8 columns]

In [ ]:
IN_OUT.to_csv(r"D:\Entertainment\Prediction of Metro Passenger Flow\Metro_train\IN_OUT21_25.csv")